### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by frank1126** [idealclover/UniTypecho#1]
你好，感谢code；
两个问题，1、下载的 release 的小程序，里面的链接被修改，无法更换链接和APPid，反复寻找后，在common里的js里 重写了url 和APPid 改了许久，很多地方无法修改 能力有限~~~
2、这个hbuilderx 有点小坑，装完要重启电脑才能用，坑~重启后，打开项目，开启小程序端口，开始编译，一直编译出错，小程序中显示app.json中定义的文件不存在，我觉得是没编译出来，还有可能是编译出的路径有问题，由于是第一次用这个软件，我的知识盲点了~在hbuilder中的错误信息是StatusCodeError: 400 - "{\"code\":40000,\"error\":\"错误 Error: ENOENT: no such file or directory, open '/Users/Apple/···/project.config.json'\"}"，这个文件的路径竟然是在项目的上一层文件夹，网络上找了很多hbuilder和小程序怎么对接的，没有找到，所以希望能出一个详细的教程，录个视频也可以呀！万分感谢~
另外 生成出来的小程序文件 非常难修改，完全不知道定义的什么引用的什么，哎

**Comment by idealclover** [comment]
啊好 之后会尝试补完教程的 最近略微有一点忙

对的 生成出来的小程序文件本身是代码压缩过的所以较难修改，一般建议是用 hbuilderx 来做然后生成

对产生的不便十分抱歉！之后会优化文档与说明的！
