### ISSUE TITLE
HbuilderX 无法运行

### ISSUE THREAD

**Issue by Snowflake-Pink** [idealclover/UniTypecho#2]
![](https://cdn.17shou.vip/2020/05/17/1d0af50db7e05.png)

如图，已经重启过，已复制 `js` 和 `json` 文件，已配置微信开发者工具路径。

**Comment by idealclover** [comment]
关闭当前项目并重新导入w

因为最开始导入的时候没有识别出manifest.json所以没认为这是个uniapp项目

**Comment by Snowflake-Pink** [comment]
OK，我还想问下 manifest.json 是否需要什么配置，我看到有APPID，教程里没有截图，有点不太清楚QwQ
